FROM python:3.10.0-alpine

WORKDIR /usr/src/app/

COPY . .

RUN apk update \
    && apk add postgresql-dev gcc python3-dev musl-dev

RUN pip install -r requirements.txt

RUN python ./manage.py collectstatic
RUN python ./manage.py makemigrations

ENTRYPOINT [ "/usr/src/app/entrypoint.sh" ]