# Generated by Django 4.1.7 on 2023-03-23 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_work_created_at_work_updated_at_alter_work_work_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='work_type',
            field=models.CharField(choices=[('dry', 'Химчистка'), ('compex', 'Комплекс'), ('polishing', 'Полировка')], max_length=30, verbose_name='Вид работы'),
        ),
    ]
